name = "hdbscan"
uuid = "4773fd7c-6dc0-4989-8854-e9e612562b10"
authors = ["Liu Felice"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
